### ISSUE TITLE
shading wrong on assignment progress page

### ISSUE THREAD

**Issue by nh357** [isaacphysics/isaac-api#184]
If a student gets a questions wrong by more than 25% then that square should go red, or that is how I understand it. Currently it also goes red when the student has got 20% of the question wrong. I'm not sure how low the wrong percentage goes before that question is no longer marked as red. 

You can see this on my assignment progress page for the Insight+ 2018/19 group, assignment: Insight+ Week 5 extra.

**Comment by jsharkey13** [comment]
This is an `isaac-app` issue, and I believe it is now fixed!
