### ISSUE TITLE
SchoolLookupConfigurationModule doesn't load custom properties file

### ISSUE THREAD

**Issue by daviesian** [isaacphysics/isaac-api#75]
It only uses the compiled-in template properties file. It should load `segue-config.properties` from `Constants.GENERAL_CONFIG_LOCATION` in the same way that [`SegueGuiceConfigurationModule`](https://github.com/ucam-cl-dtg/isaac-api/blob/master/src/main/java/uk/ac/cam/cl/dtg/segue/configuration/SegueGuiceConfigurationModule.java#L139) does.

**Comment by jsharkey13** [comment]
This all seems to be working now!
