### ISSUE TITLE
Cannot change school CSV location in segue-config.properties

### ISSUE THREAD

**Issue by daviesian** [isaacphysics/isaac-api#76]
Because Guice loads it in two different places:

* https://github.com/ucam-cl-dtg/isaac-api/blob/master/src/main/java/uk/ac/cam/cl/dtg/segue/configuration/SchoolLookupConfigurationModule.java#L67
* https://github.com/ucam-cl-dtg/isaac-api/blob/master/src/main/java/uk/ac/cam/cl/dtg/segue/configuration/SegueGuiceConfigurationModule.java#L185

This shouldn't really be the case, it should only be loaded in once place. In fact, it works as long as the two places load the same value into Guice. Because of #75, if the value is changed in a custom server config, but not in the compiled-in template config, everything explodes. 

Stop loading this value twice.

**Comment by jsharkey13** [comment]
This seems to be working after a code refactor!
