### ISSUE TITLE
Cache busting - Change build process to uniquely name css and js files

### ISSUE THREAD

**Issue by sacummins** [isaacphysics/isaac-api#85]
Ideally we want to make the css and js files created as part of a build have unique names so that we reduce the risk of caching issues when we make presentation layer changes.

**Comment by daviesian** [comment]
I have a really nice technique for this that I use for Anvil. Shouldn't be hard to reuse.

**Comment by daviesian** [comment]
Well, I say "really nice". Perhaps I meant "horrid".
```
## Add SHAs to files in /ide
RUN find /ide /runtime -type f -name "*.html" -not -path "*node_modules*" -not -path "*bower_components*" -print0 | xargs -0 sed -i -r -e '/\"\/ide([^\"]*)\?buildTime=0/s/\"/\\\"/g' -e 's/(.*\"\/ide([^\"]*))(\?buildTime=0)(.*)$/set -- `sha256sum \/ide\/app\2`;echo "\1?sha=$1\4"/eg'
```

Also, this issue is probably more applicable to `isaac-app`.

**Comment by jsharkey13** [comment]
This commit is relevant too: https://github.com/ucam-cl-dtg/isaac-app/commit/b2d8dda8454ca9a1b0992d052676d06b09ec7f49

**Comment by jsharkey13** [comment]
We've done pretty well without these!
